#!/bin/bash

set -e -u -x

RUN_DIR=/var/vcap/sys/run/telegraf-agent
LOG_DIR=/var/vcap/sys/log/telegraf-agent
STORE_DIR=/var/vcap/store/telegraf-agent
PACKAGE_DIR=/var/vcap/packages/telegraf-agent
PIDFILE=$RUN_DIR/pid

source $PACKAGE_DIR/pid_utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "telegraf-agent"

    mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR $STORE_DIR

    echo "$$" > $PIDFILE

    exec $PACKAGE_DIR/telegraf \
      -config=/var/vcap/jobs/telegraf-agent/config/telegraf.conf \
      1>>$LOG_DIR/stdout.log \
      2>>$LOG_DIR/stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: $0 {start|stop}"

    ;;

esac
